<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns="http://www.mulesource.org/schema/mule/core/2.1"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:vm="http://www.mulesource.org/schema/mule/vm/2.1"
      xmlns:test="http://www.mulesource.org/schema/mule/test/2.1"
      xmlns:scripting="http://www.mulesource.org/schema/mule/scripting/2.1"
      xsi:schemaLocation="
       http://www.mulesource.org/schema/mule/scripting/2.1 http://www.mulesource.org/schema/mule/scripting/2.1/mule-scripting.xsd
       http://www.mulesource.org/schema/mule/core/2.1 http://www.mulesource.org/schema/mule/core/2.1/mule.xsd
       http://www.mulesource.org/schema/mule/vm/2.1 http://www.mulesource.org/schema/mule/vm/2.1/mule-vm.xsd
       http://www.mulesource.org/schema/mule/test/2.1 http://www.mulesource.org/schema/mule/test/2.1/mule-test.xsd">

    <description>
        Flow for testing mule exception routing in synchronous services.
    </description>

    <custom-transformer name="exceptionToErrorResponse"
                        class="org.mule.test.integration.exceptions.ExceptionToErrorResponseTransformer"/>

    <model name="mule2-error-model">

        <default-service-exception-strategy>
            <vm:outbound-endpoint path="mule2.error" synchronous="true" remoteSync="true"/>
        </default-service-exception-strategy>

        <service name="mule2-service">
            <inbound>
                <vm:inbound-endpoint path="mule2.in" synchronous="true"/>
            </inbound>
            <scripting:component>
                <scripting:script engine="groovy">
                    throw new Exception(payload)
                </scripting:script>
            </scripting:component>
        </service>

        <service name="mule2-error-handler-service">
            <inbound>
                <vm:inbound-endpoint path="mule2.error" synchronous="true" transformer-refs="exceptionToErrorResponse"/>
            </inbound>
        </service>
    </model>

</mule>
